Use directly allocated native buffers in all gl-pointer calls, again
This was done by reverting 5789a0b, resolving conflicts and manually
fixing the camera cube part.

Using direct buffers with native byte ordering became mandatory with
increasing targetSdkVersion to 4, otherwise we get

java.lang.IllegalArgumentException: Must use a native order direct Buffer